import { makeStyles, Theme } from '@material-ui/core';

import line from "assets/img/page1/line.png";

export const usePage1Style = makeStyles((theme: Theme) => ({
  root: {
    width: '100%',
    height: '100%',
    paddingLeft: '13.8rem',
    paddingBottom: '2.5rem',
    [theme.breakpoints.down('sm')]: {
      paddingLeft: '9.5%',
      paddingBottom: '40rem',
    },
    '& .title': {
      paddingBottom: '2rem',
      width: '74.7475rem',
      color: '#0B1338',
      textShadow: '1.304px 0px 0px #B4FB56, 0px 1.304px 0px #51A7CF, 0px -1.304px 0px #AEC541, 2.609px 0px 0px rgba(73, 247, 49, 0.48)',
      fontFamily: "TT Interphases Pro Mono Trl",
      fontSize: '4rem',
      fontStyle: 'normal',
      fontWeight: 700,
      lineHeight: '4.8rem',
      background: `url(${line}) no-repeat left bottom`,
      backgroundSize: '9rem auto',
      [theme.breakpoints.down('sm')]: {
        lineHeight: '5.8rem',
        fontSize: '4.2rem',
        width: '60.8rem',
        paddingBottom: '2rem',
      },
    },
    '& .subtitle': {
      width: '69.3rem',
      marginTop: '1.8rem',
      marginBottom: '15.5rem',
      color: '#32323A',
      textShadow: '1.074px 0px 1.074px #B0FFA4',
      fontFamily: "PARADOS",
      fontSize: '2.2rem',
      fontStyle: 'normal',
      fontWeight: 400,
      lineHeight: 'normal',
      [theme.breakpoints.down('sm')]: {
        marginTop: '2rem',
        marginBottom: '3.5rem',
        fontSize: '2.4rem',
        width: '60.8rem',
      },
    },
  },
  bgBox: {
    width: '1920px',
    height: '1080px',
    [theme.breakpoints.down('sm')]: {
      width: '750px',
      height: '1334px',
    },

    '&.fit-h5': {
      '& .mark1': {
        position: 'absolute',
        top: '955px',
        left: '593px',
        width: '110px',
        height: '110px',
        flexShrink: 0,
        borderRadius: '50%',
        color: '#0B1338',
        textAlign: 'center',
        textShadow: '1.304px 0px 0px #B4FB56, 0px 1.304px 0px #51A7CF, 0px -1.304px 0px #AEC541, 2.609px 0px 0px rgba(73, 247, 49, 0.48)',
        fontFamily: 'TT Interphases Pro Mono Trl',
        fontSize: '13px',
        fontStyle: 'normal',
        fontWeight: 700,
        lineHeight: 'normal',
        letterSpacing: '-0.52px',
        textTransform: 'uppercase',

        '& span': {
          borderRadius: '50%',
          border: '12px solid #0B1338',
        },
      },
      '& .mark2': {
        position: 'absolute',
        top: '969px',
        left: '176px',
        width: '128px',
        height: '128px',
        color: '#000',
        textAlign: 'center',
        textShadow: '1.304px 0px 0px #B4FB56, 0px 1.304px 0px #51A7CF, 0px -1.304px 0px #AEC541, 2.609px 0px 0px rgba(73, 247, 49, 0.48)',
        fontFamily: 'TT Interphases Pro Mono Trl',
        fontSize: '13px',
        fontStyle: 'normal',
        fontWeight: 700,
        lineHeight: 'normal',
        textTransform: 'uppercase',
      },
      '& .mark3': {
        position: 'absolute',
        width: '178px',
        height: '178px',
        top: '735px',
        left: '491px',
        zIndex: 2,
        color: '#000',
        textAlign: 'center',
        textShadow: '1.304px 0px 0px #B4FB56, 0px 1.304px 0px #51A7CF, 0px -1.304px 0px #AEC541, 2.609px 0px 0px rgba(73, 247, 49, 0.48)',
        fontFamily: 'TT Interphases Pro Mono Trl',
        fontSize: '16px',
        fontStyle: 'normal',
        fontWeight: 700,
        lineHeight: 'normal',
        textTransform: 'uppercase',
      },
      '& .line1': {
        position: 'absolute',
        top: '1002px',
        left: '31px',
        width: '573px',
        height: '47px',
      },
      '& .line2': {
        position: 'absolute',
        top: '809.03px',
        left: '98.55px',
        width: '621px',
        height: '392px',
      },
      '& .line3': {
        position: 'absolute',
        top: '735.58px',
        left: '475.54px',
        width: '241px',
        height: '466px',
      },
      '& .line4': {
        position: 'absolute',
        top: '793px',
        left: '548px',
        width: '172px',
        height: '408px',
      },
      '& .circle1': {
        position: 'absolute',
        top: '898px',
        left: '107px',
        width: '30px',
        height: '30px',
      },
      '& .circle2': {
        position: 'absolute',
        top: '648px',
        left: '639px',
        width: '30px',
        height: '30px',
      },
      '& .dot1': {
        position: 'absolute',
        top: '226px',
        left: '45px',
        width: '10px',
        height: '10px',
      },
      '& .dot2': {
        position: 'absolute',
        top: '776px',
        left: '416px',
        width: '10px',
        height: '10px',
      },
      '& .dot3': {
        top: '1181px',
        left: '693px',
        width: '10px',
        height: '10px',
      },
      '& .triangle': {
        position: 'absolute',
        top: '889px',
        left: '336px',
        width: '23px',
        height: '21px',
      },
    },
    '&.fit-pc': {
      '& .mark1': {
        position: 'absolute',
        top: '599px',
        left: '1667.74px',

        width: '119px',
        height: '119px',
        flexShrink: 0,
        // border: '1.25px solid #0B1338',
        borderRadius: '50%',
        // padding: '4px',

        color: '#0B1338',
        textAlign: 'center',
        textShadow: '1.304px 0px 0px #B4FB56, 0px 1.304px 0px #51A7CF, 0px -1.304px 0px #AEC541, 2.609px 0px 0px rgba(73, 247, 49, 0.48)',
        fontFamily: 'TT Interphases Pro Mono Trl',
        fontSize: '14px',
        fontStyle: 'normal',
        fontWeight: 700,
        lineHeight: 'normal',
        letterSpacing: '-0.52px',
        textTransform: 'uppercase',

        '& span': {
          borderRadius: '50%',
          border: '12px solid #0B1338',
        },
      },
      '& .mark2': {
        position: 'absolute',
        top: '317.69px',
        left: '1398.17px',

        width: '138px',
        height: '139px',
        color: '#000',
        textAlign: 'center',
        textShadow: '1.304px 0px 0px #B4FB56, 0px 1.304px 0px #51A7CF, 0px -1.304px 0px #AEC541, 2.609px 0px 0px rgba(73, 247, 49, 0.48)',
        fontFamily: 'TT Interphases Pro Mono Trl',
        fontSize: '14px',
        fontStyle: 'normal',
        fontWeight: 700,
        lineHeight: 'normal',
        textTransform: 'uppercase',
      },
      '& .mark3': {
        position: 'absolute',
        top: '420.79px',
        left: '1034.1px',

        width: '192px',
        height: '192px',
        color: '#000',
        textAlign: 'center',
        textShadow: '1.304px 0px 0px #B4FB56, 0px 1.304px 0px #51A7CF, 0px -1.304px 0px #AEC541, 2.609px 0px 0px rgba(73, 247, 49, 0.48)',
        fontFamily: 'TT Interphases Pro Mono Trl',
        fontSize: '18px',
        fontStyle: 'normal',
        fontWeight: 700,
        lineHeight: 'normal',
        textTransform: 'uppercase',
      },
      '& .line1': {
        position: 'absolute',
        top: '231px',
        left: '42px',
        width: '1845px',
        height: '490px',
      },
      '& .line2': {
        position: 'absolute',
        top: '357px',
        left: '653px',
        width: '1049px',
        height: '518px',
      },
      '& .line3': {
        position: 'absolute',
        top: '189px',
        left: '945px',
        width: '364px',
        height: '689px',
      },
      '& .line4': {
        position: 'absolute',
        top: '194px',
        left: '1164px',
        width: '441px',
        height: '681px',
      },
      '& .circle1': {
        position: 'absolute',
        top: '274px',
        left: '919px',
        width: '57px',
        height: '57px',
      },
      '& .circle2': {
        position: 'absolute',
        top: '722px',
        left: '1398px',
        width: '20px',
        height: '20px',
      },
      '& .circle3': {
        position: 'absolute',
        top: '365px',
        left: '1673px',
        width: '22px',
        height: '23px',
      },
      '& .circle4': {
        position: 'absolute',
        top: '510px',
        left: '1776px',
        width: '57px',
        height: '57px',
      },
      '& .dot1': {
        position: 'absolute',
        top: '622px',
        left: '708px',
        width: '5px',
        height: '5px',
      },
      '& .dot2': {
        position: 'absolute',
        top: '707px',
        left: '868px',
        width: '9px',
        height: '9px',
      },
      '& .dot3': {
        position: 'absolute',
        top: '310px',
        left: '1194px',
        width: '8px',
        height: '8px',
      },
      '& .dot4': {
        position: 'absolute',
        top: '665px',
        left: '1259px',
        width: '12px',
        height: '12px',
      },
      '& .dot5': {
        position: 'absolute',
        top: '569px',
        left: '1555px',
        width: '11px',
        height: '10px',
      },
      '& .dot6': {
        position: 'absolute',
        top: '580px',
        left: '1563px',
        width: '5px',
        height: '6px',
      },
      '& .dot7': {
        position: 'absolute',
        top: '293px',
        left: '1663px',
        width: '5px',
        height: '5px',
      },
      '& .dot8': {
        position: 'absolute',
        top: '371px',
        left: '1822px',
        width: '12px',
        height: '12px',
      },
      '& .triangle': {
        position: 'absolute',
        top: '349px',
        left: '1279px',
        width: '24px',
        height: '24px',
      },
    },
  },
}));
