import { makeStyles, Theme } from '@material-ui/core';

import logoBg from "assets/img/page5/logoBg.png";
import logo from "assets/img/page5/logo.png";
import gif from 'assets/img/page4/logo1.gif'
import dot from "assets/img/page5/dot.png";
import dotActive from "assets/img/page5/dotActive.png";
import arrow from 'assets/img/page2/arrow.png'

export const usePage5Style = makeStyles((theme: Theme) => ({
  root: {
    width: '100%',
    height: '100%',
    paddingBottom: '10rem',
    '& .title': {
      width: '100%',
      color: '#8BDAE7',
      textShadow: '0px -1px 0.9px rgba(135, 34, 40, 0.89), 0px 3px 0.2px #090913',
      fontFamily: "TT Interphases Pro Mono Trl",
      fontSize: '4rem',
      fontStyle: 'normal',
      fontWeight: 700,
      lineHeight: '4.8rem',
      marginBottom: '2.1rem',
      [theme.breakpoints.down('sm')]: {
        width: '60.7rem',
        fontSize: '4.6rem',
        textAlign: 'center',
        lineHeight: '5.8rem',
        flexDirection: 'column',
        marginBottom: '2rem',
      },
    },
    '& .subtitle': {
      textAlign: 'center',
      width: '100%',
      marginBottom: '2rem',
      color: '#5CA6B2',
      textShadow: '1px 0px 0px rgba(176, 255, 164, 0.45)',
      fontFamily: "PARADOS",
      fontSize: '2.2rem',
      fontStyle: 'normal',
      fontWeight: 400,
      lineHeight: 'normal',
      [theme.breakpoints.down('sm')]: {
        width: '60.7rem',
        fontSize: '2.6rem',
        textAlign: 'center',
        // display: 'none',
      },
    },
    '& .tagL': {
      width: 'max-content',
      height: 'max-content',
      color: '#0C1C68',
      textShadow: '1px 0px 1px #A4EFFF, 1px 1px 1.7px rgba(109, 161, 40, 0.48)',
      fontFamily: 'Poppins',
      fontSize: '2.6rem',
      fontStyle: 'normal',
      fontWeight: '700',
      lineHeight: '1.8rem',
      padding: '1.4rem 2rem',
      display: 'flex',
      justifyContent: 'center',
      alignItems: 'center',
      background: '#8BDAE7',
      boxShadow: '6px 0px 3px 0px rgba(62, 220, 255, 0.35), 4px 0px 1px 0px rgba(46, 53, 222, 0.81), -5px 0px 4px 0px rgba(202, 255, 115, 0.44), -2px 0px 3.8px 0px #83213B',
    },
    '& .doc': {
      width: '60.3rem',
      color: '#5CA6B2',
      textShadow: '1px 0px 0px rgba(176, 255, 164, 0.45)',
      fontFamily: "PARADOS",
      fontSize: '2.2rem',
      fontStyle: 'normal',
      fontWeight: '400',
      lineHeight: 'normal',
      padding: '2rem 0',
    },
    '& .icon': {
      color: '#5CA6B2',
      textShadow: '2.091px 0px 0px rgba(176, 255, 164, 0.45)',
      fontFamily: "TT Interphases Pro Mono Trl",
      fontSize: '3.3455rem',
      fontStyle: 'normal',
      fontWeight: '700',
      lineHeight: '2.3rem',
    },
    '& .gif': {
      borderRadius: '2rem',
      width: '60.7rem',
      height: '32.8rem',
      flexShrink: 0,
      marginBottom: '6.5rem',
      background: `url(${gif}) no-repeat center`,
      backgroundSize: '110% 110%',
    },
    [theme.breakpoints.down('sm')]: {
      paddingBottom: '0',
      top: '48.5%',
      height: '82.5%',
      position: 'absolute',
      transform: 'translateY(-50%)',
      paddingTop: '14.6rem',
      justifyContent: 'flex-start',
    },
  },
  boxL: {
    width: '60.3rem',
    marginTop: '8.9rem',
    [theme.breakpoints.down('sm')]: {
      marginTop: '0',
    },
  },
  itemBox: {
    marginRight: '5rem',
    [theme.breakpoints.down('sm')]: {
      marginRight: '0',
      width: '100%',
      flexDirection: 'column',
      alignItems: 'center',
      justifyContent: 'flex-start',
    },
  },
  side: {
    display: 'none',
    // opacity: '0',
    '&.active': {
      // opacity: '1',
      display: 'block',
    }
  },
  logoBox: {
    background: `url(${logoBg}) no-repeat center 1rem`,
    backgroundSize: '100% auto',
    width: '78.3rem',
    height: '36.8782rem',
    padding: '0 7.5rem',
    marginLeft: '6.5rem',
    '& .logo': {
      position: 'relative',
      cursor: 'pointer',
      width: '66.2rem',
      height: '37.7rem',
      overflow: 'hidden',
      background: `url(${logo}) no-repeat`,
      backgroundSize: '100% 100%',
      padding: '1rem',
      '& .scroll-h': {
        borderRadius: '.5rem',
      },
      '& img': {
        width: '110%',
        height: '110%',
      },
      '& .pop': {
        opacity: 0,
        // display: 'none',
        width: '58.4rem',
        padding: '2rem 4rem',
        bottom: '.8rem',
        backgroundColor: 'rgba(11, 15, 31, 0.60)',
        filter: 'drop-shadow(0px -1px 0px rgba(140, 210, 222, 0.10))',
        backdropFilter: 'blur(1px)',

        color: '#DEDEFF',
        textShadow: '0.5px 0px 0px rgba(176, 255, 164, 0.54)',
        fontFamily: "PARADOS",
        fontSize: '1.6rem',
        fontStyle: 'normal',
        fontWeight: 700,
        lineHeight: 'normal',
        transition: '500ms all',
      },
      '&:hover .pop': {
        opacity: 1,
        // display: 'block',
      },
      [theme.breakpoints.down('sm')]: {
        width: '54.4765rem',
        height: '30.65rem',
      },
    },
    '& .tagBox': {
      width: '100%',
      top: 'calc(100% + 1.92rem)',
      '& .tag': {
        textAlign: 'center',
        color: '#8FDBEE',
        textShadow: '0px 2px 1px rgba(0, 0, 0, 0.25)',
        fontFamily: 'TT Interphases Pro Mono Trl',
        fontSize: '2.2rem',
        fontStyle: 'normal',
        fontWeight: 700,
        lineHeight: '2.8rem',
      },
      '& .subtag': {
        display: 'none',
        color: '#5CA6B2',
        textAlign: 'center',
        textShadow: '1px 0px 0px rgba(176, 255, 164, 0.45)',
        fontFamily: "PARADOS",
        fontSize: '2.2rem',
        fontStyle: 'normal',
        fontWeight: 700,
        lineHeight: 'normal',
        marginTop: '2.3rem',
        [theme.breakpoints.down('sm')]: {
          display: 'block',
        },
      }
    },
    [theme.breakpoints.down('sm')]: {
      width: '88%',
      marginLeft: '0',
      height: '30.65rem',
      background: `url(${logoBg}) no-repeat center 0`,
      backgroundSize: '100% auto',
    },
  },
  idx: {
    display: 'none',
    top: '0',
    left: '0',
    color: '#56CFE5',
    textShadow: '-3px 0px 1px rgba(222, 60, 60, 0.32), 6px -3px 0px rgba(17, 26, 255, 0.66)',
    fontFamily: 'VT323',
    fontSize: '3rem',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 'normal',
    letterSpacing: '-0.03rem',
    transform: 'translate(-100%,-100%)',
    '&.idx2': {
      [theme.breakpoints.down('sm')]: {
        left: '-2.3rem',
      },
    },
    '&.idx3': {
      [theme.breakpoints.down('sm')]: {
        left: '2.2rem',
      },
    },
    '&.idx4': {
      [theme.breakpoints.down('sm')]: {
        left: '6.5rem',
      },
    },
    [theme.breakpoints.down('sm')]: {
      left: '50%',
      transform: 'translate(-50%, 50%)',
      // position: 'relative',
      // top: '1.3rem',
      // left: '-6.6rem',
      // transform: 'none',
    },
  },
  dotBox: {
    top: '45%',
    left: '90.5%',
    gap: '2.6rem',
    '& .dot': {
      cursor: 'pointer',
      position: 'relative',
      width: '1.8rem',
      height: '1.4rem',
      background: `url(${dot}) no-repeat`,
      backgroundSize: '100% 100%',
      '&.active': {
        background: `url(${dotActive}) no-repeat`,
        backgroundSize: '100% 100%',
        '& .idx': {
          display: 'block',
        }
      },
    },
    [theme.breakpoints.down('sm')]: {
      position: 'relative',
      top: 0,
      left: 0,
      flexDirection: 'row',
      justifyContent: 'center',
      transform: 'none',
      marginTop: '25rem',
    },
  },
  swiper: {
    // padding: '0 13rem',
    // width: '161rem',
    width: '135rem',
    [theme.breakpoints.down('sm')]: {
      width: '61.6rem',
    },
    // '& .swiper-button-prev': {
    //   top: '33%',
    //   color: 'transparent',
    //   width: '4.4rem',
    //   height: '8rem',
    //   background: `url(${arrow}) no-repeat`,
    //   backgroundSize: '100% 100%',
    //   transform: 'rotate(180deg)',
    // },
    // '& .swiper-button-next': {
    //   top: '33%',
    //   color: 'transparent',
    //   width: '4.4rem',
    //   height: '8rem',
    //   background: `url(${arrow}) no-repeat`,
    //   backgroundSize: '100% 100%',
    // },
  },
  arrowBox: {
    top: '47%',
    width: '110%',
    zIndex: 2,
    pointerEvents: 'none',
    [theme.breakpoints.down('sm')]: {
      // top: '85%',
      display: 'flex',
    },
    '& .prev': {
      pointerEvents: 'auto',
      cursor: 'pointer',
      width: '4.4rem',
      height: '8rem',
      background: `url(${arrow}) no-repeat`,
      backgroundSize: '100% 100%',
      transform: 'rotate(180deg)',
    },
    '& .next': {
      pointerEvents: 'auto',
      cursor: 'pointer',
      width: '4.4rem',
      height: '8rem',
      background: `url(${arrow}) no-repeat`,
      backgroundSize: '100% 100%',
    },
  }
}));
